apiVersion: v1
kind: ConfigMap
metadata:
  name: sql-chatbot-config
data:
  AWS_REGION: "us-east-1"
  DB_SECRET_ARN: "arn:aws:secretsmanager:us-east-1:206409480438:secret:RdsStackPostgresDatabaseSec-2lEojiDqtXrV-4GVpwu"
---
apiVersion: v1
kind: Service
metadata:
  name: sql-chatbot
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8501
  selector:
    app: sql-chatbot
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sql-chatbot-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sql-chatbot
                port:
                  number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-chatbot
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: sql-chatbot
  template:
    metadata:
      labels:
        app: sql-chatbot
    spec:
      serviceAccountName: sql-chatbot-sa
      containers:
        - name: sql-chatbot
          image: CONTAINER_IMAGE
          envFrom:
            - configMapRef:
                name: sql-chatbot-config
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8501
      volumes:
        - name: tmp-volume
          emptyDir: {}